version: '2'

services:
  lbroundrobin:
    image: alizeci/dockerdemolab_lbroundrobin
    container_name: lbroundrobin
    ports:
    - "42000:6000"
  web1:
    image: alizeci/dockerdemolab_web1
    container_name: logserviceweb1
    ports:
    - "34000:6001"
  web2:
    image: alizeci/dockerdemolab_web2
    container_name: logserviceweb2
    ports:
    - "34001:6001"
  web3:
    image: alizeci/dockerdemolab_web3
    container_name: logserviceweb3
    ports:
    - "34002:6001"
  db:
    image: mongo:3.6.1
    container_name: db
    ports:
        - 27017:27017
    command: mongod
volumes:
    mongodb:
    mongodb_config: