version: '2'


services:
    db:
        image: mongo:3.6.1
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
    web:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - db
        ports:
            - "8087:6001"
        
volumes:
    mongodb:
    mongodb_config: